- name: Provision and Manage EC2 instance
  hosts: localhost
  gather_facts: yes
  roles:
    - ec2_provision
  # vars:
  #   instance_ids: "{{ ec2_instance_result.instance_ids }}"
  #   ec2_instance_state: "{{ ec2_instance_result.instances[0].state }}"  
    
  # tasks:
  #   - name: Extract public IP addresses
  #     set_fact:
  #       public_ips: "{{ ec2_instance_result.instances | map(attribute='public_ip_address') | list }}"

  #   - name: Print public IP addresses with URL
  #     debug:
  #       msg: "URL: http://{{ item }}"
  #     with_items: "{{ public_ips }}"

