- name: Provision and Manage EC2 instance
  hosts: localhost
  gather_facts: yes
  roles:
    - ec2_provision


- name: wait untill ec2 initialized
  hosts: localhost
  tasks:
    - name: Delay for 25 seconds
      pause:
        seconds: 25

- name: setup WordPress on EC2
  hosts: tag_Name_paula #webservers 
  gather_facts: yes
  become: yes
  remote_user: ubuntu
  roles:
    - wordpress       

- name: setup mysql on EC2
  hosts: tag_Name_paula 
  gather_facts: yes
  become: yes
  remote_user: ubuntu
  roles:
    - mysql                         


- name: Print EC2 Instance Endpoints
  hosts: localhost 
  gather_facts: yes
  tasks:
    - name: Print EC2 Instance Endpoints
      debug:
        msg: "EC2 Instance Endpoint: http://{{ item }}"
      with_items: "{{ public_ips }}"
      tags:
        - print_endpoints
