# roles/ec2_manager/tasks/main.yml
- name: Print instance id
  tags: [ debug ] # module is used to print debug information during the execution of the playbook.
  debug:
    msg: "Instance id is {{ instance_id }}"

- name: Start EC2 instance
  tags: [ start ]
  ec2_instance:
    # region: "{{ region }}"
    # access_key: "{{ access_key }}"
    # secret_key: "{{ secret_key }}"
    region: "us-east-1"
    access_key: "AKIAZQ3DQK2FH6EIM6X3"
    secret_key: "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"
    instance_ids: "{{ instance_id }}"
    
    state: started

- name: Stop EC2 instance
  tags: [ stop ]
  ec2_instance:
    region: "{{ region }}"
    access_key: "{{ access_key }}"
    secret_key: "{{ secret_key }}"
    instance_ids: "{{ instance_id }}"
    # region: "us-east-1"
    # access_key: "AKIAZQ3DQK2FH6EIM6X3"
    # secret_key: "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"
    state: stopped

- name: Terminate EC2 instance
  tags: [ terminate ]
  ec2_instance:
    region: "{{ region }}"
    access_key: "{{ access_key }}"
    secret_key: "{{ secret_key }}"
    instance_ids: "{{ instance_id }}"
    state: absent
