---
- name: Stop EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get EC2 instance info for "paula"
      ec2_instance_info:
        region: us-east-1
        filters:
          "tag:Name": "paula"
      register: ec2_info

    - name: Print EC2 instance info
      debug:
        var: ec2_info

    - name: Check if EC2 instance info is obtained successfully
      assert:
        that:
          - ec2_info is defined
          - ec2_info.instances | length > 0
          - ec2_info.instances | selectattr('id', 'defined') | list | length > 0
        msg: "Failed to obtain EC2 instance information for 'paula'."
      when: ec2_info is not defined or ec2_info.instances | length == 0

    - name: Stop EC2 instances
      ec2:
        instance_ids: [i-0c19c519b55f65d3e]
        state: stopped
        region: us-east-1

