---
- name: Setup WordPress on EC2
  hosts: your_ec2_instance
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - ghostscript
        - libapache2-mod-php
        - mysql-server
        - php
        - php-bcmath
        - php-curl
        - php-imagick
        - php-intl
        - php-json
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip

    - name: Clone WordPress repository
      git:
        repo: "https://{{ github_token }}@github.com/paulahakeem/WordPress_abi"
        dest: /var/www/html
      vars_files:
        - vars/github_secrets.yml
      #no_log: true  

    - name: Create Nginx virtual host file for WordPress
      template:
        src: wordpress.nginx.conf
        dest: /etc/nginx/sites-available/wordpress
      notify: Reload Nginx

    - name: Enable WordPress site
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

