- name: Create SSH Key Pair
  ec2_key:
    name: paula-ansible-key
    region: us-east-1
    key_material: "{{ lookup('file', '/home/paula/.ssh/id_ed25519.pub') }}"
  tags:
    - provision_ec2

- name: Print SSH Public Key
  debug:
    msg: "{{ lookup('file', '/home/paula/.ssh/id_ed25519.pub') }}"
  tags:
    - provision_ec2

- name: Launch EC2 instance
  ec2_instance:
    tags:
      - provision_ec2
    key_name: paula-ansible-key
    region: us-east-1
    image:
      id: ami-04b70fa74e45c3917
    instance_type: t3.small
    wait: yes
    count: 1
    tags:
      Name: paula
    #security_group: sg-044900f0bc9332e5b
    #add new sg and open port 22 443 80
    subnet_id: subnet-0d87441f0a6c423f1
    network:
      assign_public_ip: true
  register: ec2_instance_result
  tags:
    - provision_ec2

- debug:
    var: ec2_instance_result
  tags:
    - provision_ec2

- name: Add newly created EC2 instance to host group
  add_host:
    name: "{{ item.public_ip_address }}"
    groups: ec2_instances
  loop: "{{ ec2_instance_result.instances }}"
  tags:
    - provision_ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip_address }}"
    port: 22
    state: started
  loop: "{{ ec2_instance_result.instances }}"
  tags:
    - provision_ec2
