- name: Create SSH Key Pair
  amazon.aws.ec2_key:
    name: paula-ansible-key
    region: us-east-1
    key_material: "{{ lookup('file', '/home/paula/.ssh/id_ed25519.pub') }}"
  tags:
    - provision_ec2

- name: Print SSH Public Key
  debug:
    msg: "{{ lookup('file', '/home/paula/.ssh/id_ed25519.pub') }}"
  tags:
    - provision_ec2

- name: Create Security Group
  amazon.aws.ec2_group:
    name: paula-ansible-security-group
    description: "Security group with ports 22, 443, and 80 open"
    vpc_id: vpc-074ea0531b657dbb3
    region: us-east-1
    rules: "{{ security_group_rules }}"
  register: security_group
  tags:
    - provision_ec2    

- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    tags:
      - provision_ec2
    key_name: paula-ansible-key
    region: us-east-1
    image:
      id: ami-04b70fa74e45c3917
    instance_type: t3.small
    wait: yes
    count: 1
    tags:
      Name: paula
    security_group: "{{ security_group.group_id }}"  
    subnet_id: subnet-0d87441f0a6c423f1
    network:
      assign_public_ip: true
  register: ec2_instance_result
  tags:
    - provision_ec2

- debug:
    var: ec2_instance_result
  tags:
    - provision_ec2

- name: Add newly created EC2 instance to host group
  add_host:
    name: "{{ item.public_ip_address }}"
    groups: ec2_instances
  loop: "{{ ec2_instance_result.instances }}"
  tags:
    - provision_ec2

- name: Extract public IP addresses and instance IDs
  set_fact:
    public_ips: "{{ ec2_instance_result.instances | map(attribute='public_ip_address') | list }}"
    instance_ids: "{{ ec2_instance_result.instances | map(attribute='instance_id') | list }}"

- name: Write instance IDs to file
  copy:
    content: "{{ instance_ids | join('\n') }}"
    dest: "/home/paula/ansible-AWS-WordPress-Automation/instance_ids.txt"

- name: Print instance IDs
  debug:
    msg: "Instance ID: {{ item }}"
  with_items: "{{ instance_ids }}"

- name: Print public IP addresses with URL
  debug:
    msg: "URL: http://{{ item }}"
  with_items: "{{ public_ips }}"
